import React from 'react';
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Layout = ({children, title}) => {
    return (
        <div p-5>
            <Head>
                <title>PokeDex</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            
            <header className="bg-white text-black py-10 mb-10">
                <Link href="/">
                    <a>
                        <h1 className="text-6xl text-left text-black font-bold">{title}</h1>
                    </a>
                </Link>
            </header>


            <main className="container mx-auto">
                {children}
            </main>

            <footer className="flex justify-center items-center mt-10 bg-green">
                
            </footer>
        </div>
    );
};

export default Layout;
